version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
#    target-branch: "next"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
#    target-branch: "next"
    schedule:
      interval: "daily"
